name: xeus-javascript-wasm-host
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json
  - xeus-lite >= 4.0.0
  - xeus >= 2.4.0
